name: Spell Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install typos
        uses: crate-ci/typos@master
        
      - name: Run typos check
        run: typos --config ./typos.toml 